apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-cert
  namespace: default
spec:
  secretName: wisecow-tls
  duration: 2160h   # 90 days (default for Let's Encrypt)
  renewBefore: 360h # 15 days before expiry
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - wisecow.com
