name: CI/CD for Wisecow

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: Git-Runner  # private Ec2  runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository }}/wisecow:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/tls/cluster-issuer.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/ingress.yaml

